# Generated by Django 5.0.1 on 2024-02-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('ClinicId', models.AutoField(primary_key=True, serialize=False)),
                ('ClinicName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('MedecinId', models.AutoField(primary_key=True, serialize=False)),
                ('MedecinName', models.CharField(max_length=500)),
                ('Clinic', models.CharField(max_length=500)),
                ('spécialité', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('photoFileName', models.CharField(max_length=5000)),
            ],
        ),
    ]
